# fly.toml app configuration file generated for stationery on 2023-08-17T12:31:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stationery"
primary_region = "ams"

[build]
  image = "yuliafedchenko/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripleSettings__PublishableKey="pk_test_51Ng6r5BnCGUrTWo61I9hME0F6A2LLystUo6DEat2xKZqrlKM7z9ow9FuAvBmLJEMkXlHhNh8TL1zuFF9fAj4i8UU00UmaYkirZ"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
